// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace SetCodeHeaders
{
    internal sealed partial class Vsix
    {
        public const string Id = "SetCodeHeaders.39e514cd-d540-4fce-bc69-eb6f1d0b3e9b";
        public const string Name = "License Header";
        public const string Description = @"Manages license headers for you entire solution";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Louis S. Berman";
        public const string Tags = "";
    }
}
